return {
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1301033176"]={ configuration_options={ LANG="auto" }, enabled=true },
  ["workshop-1530801499"]={
    configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
    enabled=true 
  },
  ["workshop-1628298090"]={
    configuration_options={
      chesticeboxconfig=1,
      excludeitemsconfig=1,
      includecrops=1,
      includestructures=1,
      robobee_speed=4,
      robobeestatuerecipeconfig=2,
      robobeetechconfig=1,
      whentoharvest=1 
    },
    enabled=true 
  },
  ["workshop-1898292532"]={
    configuration_options={
      antlion=true,
      atrium_gate=false,
      bearger=true,
      beequeenhive=false,
      crabking=false,
      deerclops=true,
      dragonfly=false,
      hound=true,
      klaus_sack=false,
      malbatross=false,
      tips_method=1,
      toadstool=false 
    },
    enabled=true 
  },
  ["workshop-1998081438"]={ configuration_options={ StackMode=true, StackRadius=10 }, enabled=true },
  ["workshop-2114886212"]={
    configuration_options={ Blue=0, Display="target", Green=0, Projectile=true, Red=1, Type="hit" },
    enabled=true 
  },
  ["workshop-2208128427"]={
    configuration_options={
      LOOT_PUMP_EQUIP=true,
      LOOT_PUMP_SCALE=1,
      LOOT_PUMP_SOUND=true,
      LOOT_PUMP_SPEED=1,
      LOOT_PUMP_TWOZN=false,
      LOOT_PUMP_WALLS=true 
    },
    enabled=true 
  },
  ["workshop-2323630362"]={
    configuration_options={ no_rotten=true, quick_plant=true, to_auto_aligning="4*4", to_oversize=true },
    enabled=true 
  },
  ["workshop-2328604820"]={
    configuration_options={
      [""]=0,
      AUTOEQUIP=false,
      DAMAGE=27.2,
      EXTRADMG=true,
      FN_EXTRAITEMS=true,
      FN_EXTRAPICKS=true,
      FN_FASTGROWTH=true,
      FN_PICKALLFIG=false,
      LANGUAGE="zh",
      PICKER_KELP=true,
      PICKER_LICHEN=true,
      PICKER_LUREPLANT=true,
      PICKER_OCEANVINE=true,
      RADIUS=6,
      USES=75 
    },
    enabled=true 
  },
  ["workshop-356930882"]={
    configuration_options={ uses=10000000, uses2=10000000, uses3=10000000 },
    enabled=true 
  },
  ["workshop-363112314"]={ configuration_options={  }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-462372013"]={ configuration_options={  }, enabled=true },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=3,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=0,
      MOD_RESTART_CD_RESURRECT=0,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=2,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=6 
    },
    enabled=true 
  },
  ["workshop-466732225"]={ configuration_options={  }, enabled=true },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=false, EXTRASLOT=0, INVENTORYSIZE=45 },
    enabled=true 
  },
  ["workshop-796754053"]={
    configuration_options={
      boss=1,
      food=3,
      hostile=1,
      item=7,
      max_loots=20,
      min_loots=10,
      neutra=1,
      rare_1=1,
      rare_2=1,
      tumbleweed=1,
      weapon=1 
    },
    enabled=true 
  },
  ["workshop-831657598"]={ configuration_options={ stack_size=10 }, enabled=true } 
}